services:
  - type: web
    name: avantlush-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn avantlush_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: avantlush_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: SECURE_SSL_REDIRECT
        value: True

databases:
  - name: avantlush_db
    databaseName: avantlush
    user: avantlush