services:
  - type: web
    name: avantlush-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd /opt/render/project/src && gunicorn avantlush_backend.wsgi:application
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
