services:
  - type: web
    name: avantlush-backend
    env: python
    rootDirectory: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn avantlush_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "avantlush_backend.settings"
      - key: DATABASE_URL
        fromDatabase:
          name: avantlush_db
          property: connectionString
deployHooks:
  - entrypoint: python manage.py collectstatic --noinput
navigationLinks: []

databases:
  - name: avantlush_db
    databaseName: avantlush
    plan: free
