# Generated by Django 5.0.2 on 2024-12-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Waitlist Entries'},
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
