# Generated by Django 5.1.6 on 2025-02-21 13:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productvariation_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_uploads',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
