# Generated by Django 5.1.6 on 2025-02-22 08:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_image_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='variant_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
