# Generated by Django 5.1.4 on 2025-01-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(default='Nigeria', max_length=100),
        ),
    ]
