# Generated by Django 5.1.4 on 2025-01-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customuser_agreed_to_terms_customuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='agreed_to_terms',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
