# Generated by Django 5.1.6 on 2025-02-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
