# Generated by Django 5.0.2 on 2025-03-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_address_email_address_full_name_address_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.JSONField(blank=True, default=list, help_text='List of product details/features as bullet points'),
        ),
    ]
