# Generated by Django 5.0.2 on 2025-04-15 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_color_size_productvariation_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='variations', to='api.color'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='variations', to='api.size'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_variations', to='api.color'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_variations', to='api.size'),
        ),
    ]
