# Generated by Django 5.0.2 on 2025-04-15 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_productvariation_colors_productvariation_sizes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'ordering': ['order'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.RemoveField(
            model_name='carouselitem',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='carouselitem',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='carouselitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='carouselitem',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='carouselitem',
            name='title',
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
