# Generated by Django 5.0.2 on 2025-04-20 00:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_missing_crousel_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantimage',
            name='variant',
        ),
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'ordering': ['order'], 'verbose_name': 'Carousel Banner', 'verbose_name_plural': 'Carousel Banners'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_user_product_review',
        ),
        migrations.RemoveConstraint(
            model_name='reviewhelpfulvote',
            name='unique_user_review_vote',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='variant_image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='images',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='helpful_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='api.reviewtag'),
        ),
        migrations.AlterField(
            model_name='review',
            name='variant',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reviewhelpfulvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes_users', to='api.review'),
        ),
        migrations.AlterField(
            model_name='reviewtag',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviewtag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpfulvote',
            unique_together={('review', 'user')},
        ),
        migrations.DeleteModel(
            name='ProductVariantImage',
        ),
    ]
