# Generated by Django 5.0.2 on 2025-06-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_customer_country_code_customer_local_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter discount amount (percentage or fixed value based on discount type)', max_digits=5, null=True),
        ),
    ]
