# Generated by Django 5.0.2 on 2025-07-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='payment',
            name='clover_checkout_session_id',
            field=models.CharField(blank=True, help_text='Clover hosted checkout session ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='clover_checkout_url',
            field=models.URLField(blank=True, help_text='Clover hosted checkout URL', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='clover_payment_id',
            field=models.CharField(blank=True, help_text='Clover payment ID after completion', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('PAYPAL', 'PayPal'), ('GOOGLE_PAY', 'Google Pay'), ('STRIPE', 'Stripe'), ('CLOVER', 'Clover'), ('CLOVER_HOSTED', 'Clover Hosted Checkout')], max_length=20),
        ),
    ]
