# Generated by Django 5.0.2 on 2025-07-12 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clover_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CREDIT', 'Credit Card'), ('DEBIT', 'Debit Card'), ('TRANSFER', 'Bank Transfer'), ('CLOVER_HOSTED', 'Clover Hosted')], max_length=20, null=True),
        ),
    ]
