# Generated by Django 5.0.2 on 2025-08-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_ordernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
    ]
