# Generated by Django 5.0.2 on 2025-09-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_product_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
