# Generated by Django 5.0.2 on 2025-09-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_add_reserved_quantity_to_product_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, help_text="Height with unit (e.g., '30 cm', '12 inches')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, help_text="Length with unit (e.g., '25 cm', '10 inches')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, help_text="Weight with unit (e.g., '2.5 kg', '1.2 lbs')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, help_text="Width with unit (e.g., '15 cm', '6 inches')", max_length=50, null=True),
        ),
    ]
