# Generated by Django 5.0.2 on 2025-09-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_product_height_alter_product_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='shipping_type',
            field=models.CharField(choices=[('FLAT_RATE', 'Flat Rate'), ('FREE', 'Free'), ('WEIGHT_BASED', 'Weight Based'), ('DISTANCE_BASED', 'Distance Based')], default='FLAT_RATE', max_length=20),
        ),
    ]
